baseURL = "https://fenghuanghsin.github.io/"
locale = "zh-tw"
title = "星空下微風輕拂黃光閃耀的世界三"
theme = "stack"
languageCode = ""

[params]
[params.sidebar]
emoji = "🏢"
subtitle = "2025年至2038年紀錄三"

[params.sidebar.avatar]
enabled = true
local = true
src = "/img/avatar.png"

[deployment]
[[deployment]
[[deployment.targets]
name = "production"
url = "s3://fenghuanghsin?region=ap-southeast-2"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]
[menu.main]
[menu.main.params]
icon = "circle-info"

[[menu]
[[menu.main]
identifier = "about"
name = "關於"
url = "/page/about/"
weight = 7
